#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrolojiApp.Functions
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hastane")]
	public partial class UrolojiDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertbDemografikOzellikler(bDemografikOzellikler instance);
    partial void UpdatebDemografikOzellikler(bDemografikOzellikler instance);
    partial void DeletebDemografikOzellikler(bDemografikOzellikler instance);
    partial void InsertbTakipVerileri(bTakipVerileri instance);
    partial void UpdatebTakipVerileri(bTakipVerileri instance);
    partial void DeletebTakipVerileri(bTakipVerileri instance);
    partial void InsertbHastaBilgileri(bHastaBilgileri instance);
    partial void UpdatebHastaBilgileri(bHastaBilgileri instance);
    partial void DeletebHastaBilgileri(bHastaBilgileri instance);
    partial void InsertbOperatifBilgiler(bOperatifBilgiler instance);
    partial void UpdatebOperatifBilgiler(bOperatifBilgiler instance);
    partial void DeletebOperatifBilgiler(bOperatifBilgiler instance);
    partial void InsertbPatolojikVeriler(bPatolojikVeriler instance);
    partial void UpdatebPatolojikVeriler(bPatolojikVeriler instance);
    partial void DeletebPatolojikVeriler(bPatolojikVeriler instance);
    partial void InsertbPosOperatifOzellikler(bPosOperatifOzellikler instance);
    partial void UpdatebPosOperatifOzellikler(bPosOperatifOzellikler instance);
    partial void DeletebPosOperatifOzellikler(bPosOperatifOzellikler instance);
    partial void InsertbOpTuru(bOpTuru instance);
    partial void UpdatebOpTuru(bOpTuru instance);
    partial void DeletebOpTuru(bOpTuru instance);
    partial void InsertbDoctor(bDoctor instance);
    partial void UpdatebDoctor(bDoctor instance);
    partial void DeletebDoctor(bDoctor instance);
    partial void InsertbAltgrup(bAltgrup instance);
    partial void UpdatebAltgrup(bAltgrup instance);
    partial void DeletebAltgrup(bAltgrup instance);
    #endregion
		
		public UrolojiDBDataContext() : 
				base(global::UrolojiApp.Properties.Settings.Default.HastaneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UrolojiDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrolojiDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrolojiDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrolojiDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bDemografikOzellikler> bDemografikOzelliklers
		{
			get
			{
				return this.GetTable<bDemografikOzellikler>();
			}
		}
		
		public System.Data.Linq.Table<bTakipVerileri> bTakipVerileris
		{
			get
			{
				return this.GetTable<bTakipVerileri>();
			}
		}
		
		public System.Data.Linq.Table<bHastaBilgileri> bHastaBilgileris
		{
			get
			{
				return this.GetTable<bHastaBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<bOperatifBilgiler> bOperatifBilgilers
		{
			get
			{
				return this.GetTable<bOperatifBilgiler>();
			}
		}
		
		public System.Data.Linq.Table<bPatolojikVeriler> bPatolojikVerilers
		{
			get
			{
				return this.GetTable<bPatolojikVeriler>();
			}
		}
		
		public System.Data.Linq.Table<bPosOperatifOzellikler> bPosOperatifOzelliklers
		{
			get
			{
				return this.GetTable<bPosOperatifOzellikler>();
			}
		}
		
		public System.Data.Linq.Table<bOpTuru> bOpTurus
		{
			get
			{
				return this.GetTable<bOpTuru>();
			}
		}
		
		public System.Data.Linq.Table<bDoctor> bDoctors
		{
			get
			{
				return this.GetTable<bDoctor>();
			}
		}
		
		public System.Data.Linq.Table<bAltgrup> bAltgrups
		{
			get
			{
				return this.GetTable<bAltgrup>();
			}
		}
		
		public System.Data.Linq.Table<UrolojiFull> UrolojiFulls
		{
			get
			{
				return this.GetTable<UrolojiFull>();
			}
		}
		
		public System.Data.Linq.Table<patientTrackingView> patientTrackingViews
		{
			get
			{
				return this.GetTable<patientTrackingView>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bDemografikOzellikler")]
	public partial class bDemografikOzellikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<int> _Boy;
		
		private System.Nullable<decimal> _Kilo;
		
		private System.Nullable<decimal> _BMI;
		
		private System.Nullable<int> _ASA;
		
		private string _DrAdi;
		
		private string _Cinsiyet;
		
		private string _Taraf;
		
		private string _Lokalizasyon;
		
		private string _Boyut;
		
		private string _KoMorbidite;
		
		private System.Nullable<int> _HastaID;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnYasChanging(System.Nullable<int> value);
    partial void OnYasChanged();
    partial void OnBoyChanging(System.Nullable<int> value);
    partial void OnBoyChanged();
    partial void OnKiloChanging(System.Nullable<decimal> value);
    partial void OnKiloChanged();
    partial void OnBMIChanging(System.Nullable<decimal> value);
    partial void OnBMIChanged();
    partial void OnASAChanging(System.Nullable<int> value);
    partial void OnASAChanged();
    partial void OnDrAdiChanging(string value);
    partial void OnDrAdiChanged();
    partial void OnCinsiyetChanging(string value);
    partial void OnCinsiyetChanged();
    partial void OnTarafChanging(string value);
    partial void OnTarafChanged();
    partial void OnLokalizasyonChanging(string value);
    partial void OnLokalizasyonChanged();
    partial void OnBoyutChanging(string value);
    partial void OnBoyutChanged();
    partial void OnKoMorbiditeChanging(string value);
    partial void OnKoMorbiditeChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    #endregion
		
		public bDemografikOzellikler()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this.OnYasChanging(value);
					this.SendPropertyChanging();
					this._Yas = value;
					this.SendPropertyChanged("Yas");
					this.OnYasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boy", DbType="Int")]
		public System.Nullable<int> Boy
		{
			get
			{
				return this._Boy;
			}
			set
			{
				if ((this._Boy != value))
				{
					this.OnBoyChanging(value);
					this.SendPropertyChanging();
					this._Boy = value;
					this.SendPropertyChanged("Boy");
					this.OnBoyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Kilo
		{
			get
			{
				return this._Kilo;
			}
			set
			{
				if ((this._Kilo != value))
				{
					this.OnKiloChanging(value);
					this.SendPropertyChanging();
					this._Kilo = value;
					this.SendPropertyChanged("Kilo");
					this.OnKiloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASA", DbType="Int")]
		public System.Nullable<int> ASA
		{
			get
			{
				return this._ASA;
			}
			set
			{
				if ((this._ASA != value))
				{
					this.OnASAChanging(value);
					this.SendPropertyChanging();
					this._ASA = value;
					this.SendPropertyChanged("ASA");
					this.OnASAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrAdi", DbType="NVarChar(200)")]
		public string DrAdi
		{
			get
			{
				return this._DrAdi;
			}
			set
			{
				if ((this._DrAdi != value))
				{
					this.OnDrAdiChanging(value);
					this.SendPropertyChanging();
					this._DrAdi = value;
					this.SendPropertyChanged("DrAdi");
					this.OnDrAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="NVarChar(2)")]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(2)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this.OnTarafChanging(value);
					this.SendPropertyChanging();
					this._Taraf = value;
					this.SendPropertyChanged("Taraf");
					this.OnTarafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizasyon", DbType="NVarChar(250)")]
		public string Lokalizasyon
		{
			get
			{
				return this._Lokalizasyon;
			}
			set
			{
				if ((this._Lokalizasyon != value))
				{
					this.OnLokalizasyonChanging(value);
					this.SendPropertyChanging();
					this._Lokalizasyon = value;
					this.SendPropertyChanged("Lokalizasyon");
					this.OnLokalizasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="NVarChar(50)")]
		public string Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoMorbidite", DbType="NVarChar(100)")]
		public string KoMorbidite
		{
			get
			{
				return this._KoMorbidite;
			}
			set
			{
				if ((this._KoMorbidite != value))
				{
					this.OnKoMorbiditeChanging(value);
					this.SendPropertyChanging();
					this._KoMorbidite = value;
					this.SendPropertyChanged("KoMorbidite");
					this.OnKoMorbiditeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bDemografikOzellikler", Storage="_bHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bDemografikOzelliklers.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bDemografikOzelliklers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bTakipVerileri")]
	public partial class bTakipVerileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PostOp3AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp3AyKreatin;
		
		private string _PostOp6AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp6AyKreatin;
		
		private string _PostOp12AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp12AyKreatin;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPostOp3AyLokalNuksChanging(string value);
    partial void OnPostOp3AyLokalNuksChanged();
    partial void OnPostOp3AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostOp3AyKreatinChanged();
    partial void OnPostOp6AyLokalNuksChanging(string value);
    partial void OnPostOp6AyLokalNuksChanged();
    partial void OnPostOp6AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostOp6AyKreatinChanged();
    partial void OnPostOp12AyLokalNuksChanging(string value);
    partial void OnPostOp12AyLokalNuksChanged();
    partial void OnPostOp12AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostOp12AyKreatinChanged();
    #endregion
		
		public bTakipVerileri()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp3AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp3AyLokalNuks
		{
			get
			{
				return this._PostOp3AyLokalNuks;
			}
			set
			{
				if ((this._PostOp3AyLokalNuks != value))
				{
					this.OnPostOp3AyLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._PostOp3AyLokalNuks = value;
					this.SendPropertyChanged("PostOp3AyLokalNuks");
					this.OnPostOp3AyLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp3AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp3AyKreatin
		{
			get
			{
				return this._PostOp3AyKreatin;
			}
			set
			{
				if ((this._PostOp3AyKreatin != value))
				{
					this.OnPostOp3AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostOp3AyKreatin = value;
					this.SendPropertyChanged("PostOp3AyKreatin");
					this.OnPostOp3AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp6AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp6AyLokalNuks
		{
			get
			{
				return this._PostOp6AyLokalNuks;
			}
			set
			{
				if ((this._PostOp6AyLokalNuks != value))
				{
					this.OnPostOp6AyLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._PostOp6AyLokalNuks = value;
					this.SendPropertyChanged("PostOp6AyLokalNuks");
					this.OnPostOp6AyLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp6AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp6AyKreatin
		{
			get
			{
				return this._PostOp6AyKreatin;
			}
			set
			{
				if ((this._PostOp6AyKreatin != value))
				{
					this.OnPostOp6AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostOp6AyKreatin = value;
					this.SendPropertyChanged("PostOp6AyKreatin");
					this.OnPostOp6AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp12AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp12AyLokalNuks
		{
			get
			{
				return this._PostOp12AyLokalNuks;
			}
			set
			{
				if ((this._PostOp12AyLokalNuks != value))
				{
					this.OnPostOp12AyLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._PostOp12AyLokalNuks = value;
					this.SendPropertyChanged("PostOp12AyLokalNuks");
					this.OnPostOp12AyLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp12AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp12AyKreatin
		{
			get
			{
				return this._PostOp12AyKreatin;
			}
			set
			{
				if ((this._PostOp12AyKreatin != value))
				{
					this.OnPostOp12AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostOp12AyKreatin = value;
					this.SendPropertyChanged("PostOp12AyKreatin");
					this.OnPostOp12AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bTakipVerileri", Storage="_bHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bTakipVerileris.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bTakipVerileris.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bHastaBilgileri")]
	public partial class bHastaBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HastaAdı;
		
		private string _HastaSoyadı;
		
		private string _ProtokolNo;
		
		private System.Nullable<System.DateTime> _OperasyonTarihi;
		
		private string _OpTuru;
		
		private System.Nullable<int> _TakipAy;
		
		private System.Nullable<int> _Anah;
		
		private EntitySet<bDemografikOzellikler> _bDemografikOzelliklers;
		
		private EntitySet<bTakipVerileri> _bTakipVerileris;
		
		private EntitySet<bOperatifBilgiler> _bOperatifBilgilers;
		
		private EntitySet<bPatolojikVeriler> _bPatolojikVerilers;
		
		private EntitySet<bPosOperatifOzellikler> _bPosOperatifOzelliklers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaAdıChanging(string value);
    partial void OnHastaAdıChanged();
    partial void OnHastaSoyadıChanging(string value);
    partial void OnHastaSoyadıChanged();
    partial void OnProtokolNoChanging(string value);
    partial void OnProtokolNoChanged();
    partial void OnOperasyonTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOperasyonTarihiChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    partial void OnTakipAyChanging(System.Nullable<int> value);
    partial void OnTakipAyChanged();
    partial void OnAnahChanging(System.Nullable<int> value);
    partial void OnAnahChanged();
    #endregion
		
		public bHastaBilgileri()
		{
			this._bDemografikOzelliklers = new EntitySet<bDemografikOzellikler>(new Action<bDemografikOzellikler>(this.attach_bDemografikOzelliklers), new Action<bDemografikOzellikler>(this.detach_bDemografikOzelliklers));
			this._bTakipVerileris = new EntitySet<bTakipVerileri>(new Action<bTakipVerileri>(this.attach_bTakipVerileris), new Action<bTakipVerileri>(this.detach_bTakipVerileris));
			this._bOperatifBilgilers = new EntitySet<bOperatifBilgiler>(new Action<bOperatifBilgiler>(this.attach_bOperatifBilgilers), new Action<bOperatifBilgiler>(this.detach_bOperatifBilgilers));
			this._bPatolojikVerilers = new EntitySet<bPatolojikVeriler>(new Action<bPatolojikVeriler>(this.attach_bPatolojikVerilers), new Action<bPatolojikVeriler>(this.detach_bPatolojikVerilers));
			this._bPosOperatifOzelliklers = new EntitySet<bPosOperatifOzellikler>(new Action<bPosOperatifOzellikler>(this.attach_bPosOperatifOzelliklers), new Action<bPosOperatifOzellikler>(this.detach_bPosOperatifOzelliklers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaAdı", DbType="NVarChar(50)")]
		public string HastaAdı
		{
			get
			{
				return this._HastaAdı;
			}
			set
			{
				if ((this._HastaAdı != value))
				{
					this.OnHastaAdıChanging(value);
					this.SendPropertyChanging();
					this._HastaAdı = value;
					this.SendPropertyChanged("HastaAdı");
					this.OnHastaAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaSoyadı", DbType="NVarChar(50)")]
		public string HastaSoyadı
		{
			get
			{
				return this._HastaSoyadı;
			}
			set
			{
				if ((this._HastaSoyadı != value))
				{
					this.OnHastaSoyadıChanging(value);
					this.SendPropertyChanging();
					this._HastaSoyadı = value;
					this.SendPropertyChanged("HastaSoyadı");
					this.OnHastaSoyadıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProtokolNo", DbType="NVarChar(50)")]
		public string ProtokolNo
		{
			get
			{
				return this._ProtokolNo;
			}
			set
			{
				if ((this._ProtokolNo != value))
				{
					this.OnProtokolNoChanging(value);
					this.SendPropertyChanging();
					this._ProtokolNo = value;
					this.SendPropertyChanged("ProtokolNo");
					this.OnProtokolNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperasyonTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> OperasyonTarihi
		{
			get
			{
				return this._OperasyonTarihi;
			}
			set
			{
				if ((this._OperasyonTarihi != value))
				{
					this.OnOperasyonTarihiChanging(value);
					this.SendPropertyChanging();
					this._OperasyonTarihi = value;
					this.SendPropertyChanged("OperasyonTarihi");
					this.OnOperasyonTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(400)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakipAy", DbType="Int")]
		public System.Nullable<int> TakipAy
		{
			get
			{
				return this._TakipAy;
			}
			set
			{
				if ((this._TakipAy != value))
				{
					this.OnTakipAyChanging(value);
					this.SendPropertyChanging();
					this._TakipAy = value;
					this.SendPropertyChanged("TakipAy");
					this.OnTakipAyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this.OnAnahChanging(value);
					this.SendPropertyChanging();
					this._Anah = value;
					this.SendPropertyChanged("Anah");
					this.OnAnahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bDemografikOzellikler", Storage="_bDemografikOzelliklers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<bDemografikOzellikler> bDemografikOzelliklers
		{
			get
			{
				return this._bDemografikOzelliklers;
			}
			set
			{
				this._bDemografikOzelliklers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bTakipVerileri", Storage="_bTakipVerileris", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<bTakipVerileri> bTakipVerileris
		{
			get
			{
				return this._bTakipVerileris;
			}
			set
			{
				this._bTakipVerileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bOperatifBilgiler", Storage="_bOperatifBilgilers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<bOperatifBilgiler> bOperatifBilgilers
		{
			get
			{
				return this._bOperatifBilgilers;
			}
			set
			{
				this._bOperatifBilgilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bPatolojikVeriler", Storage="_bPatolojikVerilers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<bPatolojikVeriler> bPatolojikVerilers
		{
			get
			{
				return this._bPatolojikVerilers;
			}
			set
			{
				this._bPatolojikVerilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bPosOperatifOzellikler", Storage="_bPosOperatifOzelliklers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<bPosOperatifOzellikler> bPosOperatifOzelliklers
		{
			get
			{
				return this._bPosOperatifOzelliklers;
			}
			set
			{
				this._bPosOperatifOzelliklers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bDemografikOzelliklers(bDemografikOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bDemografikOzelliklers(bDemografikOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
		
		private void attach_bTakipVerileris(bTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bTakipVerileris(bTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
		
		private void attach_bOperatifBilgilers(bOperatifBilgiler entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bOperatifBilgilers(bOperatifBilgiler entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
		
		private void attach_bPatolojikVerilers(bPatolojikVeriler entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bPatolojikVerilers(bPatolojikVeriler entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
		
		private void attach_bPosOperatifOzelliklers(bPosOperatifOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bPosOperatifOzelliklers(bPosOperatifOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bOperatifBilgiler")]
	public partial class bOperatifBilgiler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PksAciklamasi;
		
		private string _Sikayet;
		
		private string _CoOperasyon;
		
		private System.Nullable<int> _Iskemi;
		
		private System.Nullable<int> _PortSayisi;
		
		private string _YardimYNT;
		
		private System.Nullable<int> _Sure;
		
		private string _Dren;
		
		private System.Nullable<int> _Kanama;
		
		private System.Nullable<int> _Piyes;
		
		private System.Nullable<int> _HastaID;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPksAciklamasiChanging(string value);
    partial void OnPksAciklamasiChanged();
    partial void OnSikayetChanging(string value);
    partial void OnSikayetChanged();
    partial void OnCoOperasyonChanging(string value);
    partial void OnCoOperasyonChanged();
    partial void OnIskemiChanging(System.Nullable<int> value);
    partial void OnIskemiChanged();
    partial void OnPortSayisiChanging(System.Nullable<int> value);
    partial void OnPortSayisiChanged();
    partial void OnYardimYNTChanging(string value);
    partial void OnYardimYNTChanged();
    partial void OnSureChanging(System.Nullable<int> value);
    partial void OnSureChanged();
    partial void OnDrenChanging(string value);
    partial void OnDrenChanged();
    partial void OnKanamaChanging(System.Nullable<int> value);
    partial void OnKanamaChanged();
    partial void OnPiyesChanging(System.Nullable<int> value);
    partial void OnPiyesChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    #endregion
		
		public bOperatifBilgiler()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PksAciklamasi", DbType="NVarChar(2)")]
		public string PksAciklamasi
		{
			get
			{
				return this._PksAciklamasi;
			}
			set
			{
				if ((this._PksAciklamasi != value))
				{
					this.OnPksAciklamasiChanging(value);
					this.SendPropertyChanging();
					this._PksAciklamasi = value;
					this.SendPropertyChanged("PksAciklamasi");
					this.OnPksAciklamasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sikayet", DbType="NVarChar(50)")]
		public string Sikayet
		{
			get
			{
				return this._Sikayet;
			}
			set
			{
				if ((this._Sikayet != value))
				{
					this.OnSikayetChanging(value);
					this.SendPropertyChanging();
					this._Sikayet = value;
					this.SendPropertyChanged("Sikayet");
					this.OnSikayetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoOperasyon", DbType="NVarChar(150)")]
		public string CoOperasyon
		{
			get
			{
				return this._CoOperasyon;
			}
			set
			{
				if ((this._CoOperasyon != value))
				{
					this.OnCoOperasyonChanging(value);
					this.SendPropertyChanging();
					this._CoOperasyon = value;
					this.SendPropertyChanged("CoOperasyon");
					this.OnCoOperasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iskemi", DbType="Int")]
		public System.Nullable<int> Iskemi
		{
			get
			{
				return this._Iskemi;
			}
			set
			{
				if ((this._Iskemi != value))
				{
					this.OnIskemiChanging(value);
					this.SendPropertyChanging();
					this._Iskemi = value;
					this.SendPropertyChanged("Iskemi");
					this.OnIskemiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortSayisi", DbType="Int")]
		public System.Nullable<int> PortSayisi
		{
			get
			{
				return this._PortSayisi;
			}
			set
			{
				if ((this._PortSayisi != value))
				{
					this.OnPortSayisiChanging(value);
					this.SendPropertyChanging();
					this._PortSayisi = value;
					this.SendPropertyChanged("PortSayisi");
					this.OnPortSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YardimYNT", DbType="NVarChar(55)")]
		public string YardimYNT
		{
			get
			{
				return this._YardimYNT;
			}
			set
			{
				if ((this._YardimYNT != value))
				{
					this.OnYardimYNTChanging(value);
					this.SendPropertyChanging();
					this._YardimYNT = value;
					this.SendPropertyChanged("YardimYNT");
					this.OnYardimYNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="NVarChar(50)")]
		public string Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kanama", DbType="Int")]
		public System.Nullable<int> Kanama
		{
			get
			{
				return this._Kanama;
			}
			set
			{
				if ((this._Kanama != value))
				{
					this.OnKanamaChanging(value);
					this.SendPropertyChanging();
					this._Kanama = value;
					this.SendPropertyChanged("Kanama");
					this.OnKanamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piyes", DbType="Int")]
		public System.Nullable<int> Piyes
		{
			get
			{
				return this._Piyes;
			}
			set
			{
				if ((this._Piyes != value))
				{
					this.OnPiyesChanging(value);
					this.SendPropertyChanging();
					this._Piyes = value;
					this.SendPropertyChanged("Piyes");
					this.OnPiyesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bOperatifBilgiler", Storage="_bHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bOperatifBilgilers.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bOperatifBilgilers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bPatolojikVeriler")]
	public partial class bPatolojikVeriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _Patoloji;
		
		private string _AltGrup;
		
		private string _FuhrmanGrade;
		
		private string _PatolojikEvreler;
		
		private string _CerrahiSinir;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    partial void OnAltGrupChanging(string value);
    partial void OnAltGrupChanged();
    partial void OnFuhrmanGradeChanging(string value);
    partial void OnFuhrmanGradeChanged();
    partial void OnPatolojikEvrelerChanging(string value);
    partial void OnPatolojikEvrelerChanged();
    partial void OnCerrahiSinirChanging(string value);
    partial void OnCerrahiSinirChanged();
    #endregion
		
		public bPatolojikVeriler()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(50)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(100)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this.OnAltGrupChanging(value);
					this.SendPropertyChanging();
					this._AltGrup = value;
					this.SendPropertyChanged("AltGrup");
					this.OnAltGrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuhrmanGrade", DbType="NVarChar(30)")]
		public string FuhrmanGrade
		{
			get
			{
				return this._FuhrmanGrade;
			}
			set
			{
				if ((this._FuhrmanGrade != value))
				{
					this.OnFuhrmanGradeChanging(value);
					this.SendPropertyChanging();
					this._FuhrmanGrade = value;
					this.SendPropertyChanged("FuhrmanGrade");
					this.OnFuhrmanGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatolojikEvreler", DbType="NVarChar(10)")]
		public string PatolojikEvreler
		{
			get
			{
				return this._PatolojikEvreler;
			}
			set
			{
				if ((this._PatolojikEvreler != value))
				{
					this.OnPatolojikEvrelerChanging(value);
					this.SendPropertyChanging();
					this._PatolojikEvreler = value;
					this.SendPropertyChanged("PatolojikEvreler");
					this.OnPatolojikEvrelerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerrahiSinir", DbType="NVarChar(2)")]
		public string CerrahiSinir
		{
			get
			{
				return this._CerrahiSinir;
			}
			set
			{
				if ((this._CerrahiSinir != value))
				{
					this.OnCerrahiSinirChanging(value);
					this.SendPropertyChanging();
					this._CerrahiSinir = value;
					this.SendPropertyChanged("CerrahiSinir");
					this.OnCerrahiSinirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bPatolojikVeriler", Storage="_bHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bPatolojikVerilers.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bPatolojikVerilers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bPosOperatifOzellikler")]
	public partial class bPosOperatifOzellikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PreOpveErkenKomp;
		
		private string _PostOpAnaliz;
		
		private string _Sonda;
		
		private System.Nullable<int> _HospSuresi;
		
		private System.Nullable<decimal> _PreOpKreatin;
		
		private System.Nullable<decimal> _PostOpKreatin;
		
		private System.Nullable<decimal> _PreOpHCT;
		
		private System.Nullable<decimal> _PostOpHCT;
		
		private System.Nullable<decimal> _PreOpHB;
		
		private System.Nullable<decimal> _PostOpHB;
		
		private string _Takip;
		
		private string _Tel;
		
		private string _PostOpGecKomp;
		
		private string _KompClavien;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPreOpveErkenKompChanging(string value);
    partial void OnPreOpveErkenKompChanged();
    partial void OnPostOpAnalizChanging(string value);
    partial void OnPostOpAnalizChanged();
    partial void OnSondaChanging(string value);
    partial void OnSondaChanged();
    partial void OnHospSuresiChanging(System.Nullable<int> value);
    partial void OnHospSuresiChanged();
    partial void OnPreOpKreatinChanging(System.Nullable<decimal> value);
    partial void OnPreOpKreatinChanged();
    partial void OnPostOpKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostOpKreatinChanged();
    partial void OnPreOpHCTChanging(System.Nullable<decimal> value);
    partial void OnPreOpHCTChanged();
    partial void OnPostOpHCTChanging(System.Nullable<decimal> value);
    partial void OnPostOpHCTChanged();
    partial void OnPreOpHBChanging(System.Nullable<decimal> value);
    partial void OnPreOpHBChanged();
    partial void OnPostOpHBChanging(System.Nullable<decimal> value);
    partial void OnPostOpHBChanged();
    partial void OnTakipChanging(string value);
    partial void OnTakipChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnPostOpGecKompChanging(string value);
    partial void OnPostOpGecKompChanged();
    partial void OnKompClavienChanging(string value);
    partial void OnKompClavienChanged();
    #endregion
		
		public bPosOperatifOzellikler()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpveErkenKomp", DbType="NVarChar(50)")]
		public string PreOpveErkenKomp
		{
			get
			{
				return this._PreOpveErkenKomp;
			}
			set
			{
				if ((this._PreOpveErkenKomp != value))
				{
					this.OnPreOpveErkenKompChanging(value);
					this.SendPropertyChanging();
					this._PreOpveErkenKomp = value;
					this.SendPropertyChanged("PreOpveErkenKomp");
					this.OnPreOpveErkenKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpAnaliz", DbType="NVarChar(50)")]
		public string PostOpAnaliz
		{
			get
			{
				return this._PostOpAnaliz;
			}
			set
			{
				if ((this._PostOpAnaliz != value))
				{
					this.OnPostOpAnalizChanging(value);
					this.SendPropertyChanging();
					this._PostOpAnaliz = value;
					this.SendPropertyChanged("PostOpAnaliz");
					this.OnPostOpAnalizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonda", DbType="NVarChar(50)")]
		public string Sonda
		{
			get
			{
				return this._Sonda;
			}
			set
			{
				if ((this._Sonda != value))
				{
					this.OnSondaChanging(value);
					this.SendPropertyChanging();
					this._Sonda = value;
					this.SendPropertyChanged("Sonda");
					this.OnSondaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospSuresi", DbType="Int")]
		public System.Nullable<int> HospSuresi
		{
			get
			{
				return this._HospSuresi;
			}
			set
			{
				if ((this._HospSuresi != value))
				{
					this.OnHospSuresiChanging(value);
					this.SendPropertyChanging();
					this._HospSuresi = value;
					this.SendPropertyChanged("HospSuresi");
					this.OnHospSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PreOpKreatin
		{
			get
			{
				return this._PreOpKreatin;
			}
			set
			{
				if ((this._PreOpKreatin != value))
				{
					this.OnPreOpKreatinChanging(value);
					this.SendPropertyChanging();
					this._PreOpKreatin = value;
					this.SendPropertyChanged("PreOpKreatin");
					this.OnPreOpKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PostOpKreatin
		{
			get
			{
				return this._PostOpKreatin;
			}
			set
			{
				if ((this._PostOpKreatin != value))
				{
					this.OnPostOpKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostOpKreatin = value;
					this.SendPropertyChanged("PostOpKreatin");
					this.OnPostOpKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpHCT", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PreOpHCT
		{
			get
			{
				return this._PreOpHCT;
			}
			set
			{
				if ((this._PreOpHCT != value))
				{
					this.OnPreOpHCTChanging(value);
					this.SendPropertyChanging();
					this._PreOpHCT = value;
					this.SendPropertyChanged("PreOpHCT");
					this.OnPreOpHCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpHCT", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PostOpHCT
		{
			get
			{
				return this._PostOpHCT;
			}
			set
			{
				if ((this._PostOpHCT != value))
				{
					this.OnPostOpHCTChanging(value);
					this.SendPropertyChanging();
					this._PostOpHCT = value;
					this.SendPropertyChanged("PostOpHCT");
					this.OnPostOpHCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpHB", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PreOpHB
		{
			get
			{
				return this._PreOpHB;
			}
			set
			{
				if ((this._PreOpHB != value))
				{
					this.OnPreOpHBChanging(value);
					this.SendPropertyChanging();
					this._PreOpHB = value;
					this.SendPropertyChanged("PreOpHB");
					this.OnPreOpHBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpHB", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PostOpHB
		{
			get
			{
				return this._PostOpHB;
			}
			set
			{
				if ((this._PostOpHB != value))
				{
					this.OnPostOpHBChanging(value);
					this.SendPropertyChanging();
					this._PostOpHB = value;
					this.SendPropertyChanged("PostOpHB");
					this.OnPostOpHBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="NVarChar(175)")]
		public string Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(20)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpGecKomp", DbType="NVarChar(100)")]
		public string PostOpGecKomp
		{
			get
			{
				return this._PostOpGecKomp;
			}
			set
			{
				if ((this._PostOpGecKomp != value))
				{
					this.OnPostOpGecKompChanging(value);
					this.SendPropertyChanging();
					this._PostOpGecKomp = value;
					this.SendPropertyChanged("PostOpGecKomp");
					this.OnPostOpGecKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompClavien", DbType="NVarChar(5)")]
		public string KompClavien
		{
			get
			{
				return this._KompClavien;
			}
			set
			{
				if ((this._KompClavien != value))
				{
					this.OnKompClavienChanging(value);
					this.SendPropertyChanging();
					this._KompClavien = value;
					this.SendPropertyChanged("KompClavien");
					this.OnKompClavienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bPosOperatifOzellikler", Storage="_bHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bPosOperatifOzelliklers.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bPosOperatifOzelliklers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bOpTuru")]
	public partial class bOpTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _OpName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnOpNameChanging(string value);
    partial void OnOpNameChanged();
    #endregion
		
		public bOpTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpName", DbType="NVarChar(50)")]
		public string OpName
		{
			get
			{
				return this._OpName;
			}
			set
			{
				if ((this._OpName != value))
				{
					this.OnOpNameChanging(value);
					this.SendPropertyChanging();
					this._OpName = value;
					this.SendPropertyChanged("OpName");
					this.OnOpNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bDoctors")]
	public partial class bDoctor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DrName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDrNameChanging(string value);
    partial void OnDrNameChanged();
    #endregion
		
		public bDoctor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrName", DbType="NVarChar(100)")]
		public string DrName
		{
			get
			{
				return this._DrName;
			}
			set
			{
				if ((this._DrName != value))
				{
					this.OnDrNameChanging(value);
					this.SendPropertyChanging();
					this._DrName = value;
					this.SendPropertyChanged("DrName");
					this.OnDrNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bAltgrup")]
	public partial class bAltgrup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Altgrup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAltgrupChanging(string value);
    partial void OnAltgrupChanged();
    #endregion
		
		public bAltgrup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Altgrup", DbType="NVarChar(100)")]
		public string Altgrup
		{
			get
			{
				return this._Altgrup;
			}
			set
			{
				if ((this._Altgrup != value))
				{
					this.OnAltgrupChanging(value);
					this.SendPropertyChanging();
					this._Altgrup = value;
					this.SendPropertyChanged("Altgrup");
					this.OnAltgrupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UrolojiFull")]
	public partial class UrolojiFull
	{
		
		private int _ID;
		
		private string _HastaAdı;
		
		private string _HastaSoyadı;
		
		private string _ProtokolNo;
		
		private System.Nullable<System.DateTime> _OperasyonTarihi;
		
		private string _OpTuru;
		
		private System.Nullable<int> _TakipAy;
		
		private System.Nullable<int> _Anah;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<int> _Boy;
		
		private System.Nullable<decimal> _Kilo;
		
		private System.Nullable<decimal> _BMI;
		
		private System.Nullable<int> _ASA;
		
		private string _DrAdi;
		
		private string _Cinsiyet;
		
		private string _Taraf;
		
		private string _Lokalizasyon;
		
		private string _Boyut;
		
		private string _KoMorbidite;
		
		private string _PksAciklamasi;
		
		private string _Sikayet;
		
		private string _CoOperasyon;
		
		private System.Nullable<int> _Iskemi;
		
		private System.Nullable<int> _PortSayisi;
		
		private string _YardimYNT;
		
		private System.Nullable<int> _Sure;
		
		private string _Dren;
		
		private System.Nullable<int> _Kanama;
		
		private System.Nullable<int> _Piyes;
		
		private string _PreOpveErkenKomp;
		
		private string _PostOpAnaliz;
		
		private string _Sonda;
		
		private System.Nullable<int> _HospSuresi;
		
		private System.Nullable<decimal> _PreOpKreatin;
		
		private System.Nullable<decimal> _PostOpKreatin;
		
		private System.Nullable<decimal> _PreOpHCT;
		
		private System.Nullable<decimal> _PostOpHCT;
		
		private System.Nullable<decimal> _PreOpHB;
		
		private System.Nullable<decimal> _PostOpHB;
		
		private string _Takip;
		
		private string _Tel;
		
		private string _PostOpGecKomp;
		
		private string _KompClavien;
		
		private string _Patoloji;
		
		private string _AltGrup;
		
		private string _FuhrmanGrade;
		
		private string _PatolojikEvreler;
		
		private string _CerrahiSinir;
		
		private string _PostOp3AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp3AyKreatin;
		
		private string _PostOp6AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp6AyKreatin;
		
		private string _PostOp12AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp12AyKreatin;
		
		public UrolojiFull()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaAdı", DbType="NVarChar(50)")]
		public string HastaAdı
		{
			get
			{
				return this._HastaAdı;
			}
			set
			{
				if ((this._HastaAdı != value))
				{
					this._HastaAdı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaSoyadı", DbType="NVarChar(50)")]
		public string HastaSoyadı
		{
			get
			{
				return this._HastaSoyadı;
			}
			set
			{
				if ((this._HastaSoyadı != value))
				{
					this._HastaSoyadı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProtokolNo", DbType="NVarChar(50)")]
		public string ProtokolNo
		{
			get
			{
				return this._ProtokolNo;
			}
			set
			{
				if ((this._ProtokolNo != value))
				{
					this._ProtokolNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperasyonTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> OperasyonTarihi
		{
			get
			{
				return this._OperasyonTarihi;
			}
			set
			{
				if ((this._OperasyonTarihi != value))
				{
					this._OperasyonTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(400)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this._OpTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakipAy", DbType="Int")]
		public System.Nullable<int> TakipAy
		{
			get
			{
				return this._TakipAy;
			}
			set
			{
				if ((this._TakipAy != value))
				{
					this._TakipAy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this._Anah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this._Yas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boy", DbType="Int")]
		public System.Nullable<int> Boy
		{
			get
			{
				return this._Boy;
			}
			set
			{
				if ((this._Boy != value))
				{
					this._Boy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Kilo
		{
			get
			{
				return this._Kilo;
			}
			set
			{
				if ((this._Kilo != value))
				{
					this._Kilo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this._BMI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASA", DbType="Int")]
		public System.Nullable<int> ASA
		{
			get
			{
				return this._ASA;
			}
			set
			{
				if ((this._ASA != value))
				{
					this._ASA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrAdi", DbType="NVarChar(200)")]
		public string DrAdi
		{
			get
			{
				return this._DrAdi;
			}
			set
			{
				if ((this._DrAdi != value))
				{
					this._DrAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="NVarChar(2)")]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this._Cinsiyet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(2)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this._Taraf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizasyon", DbType="NVarChar(250)")]
		public string Lokalizasyon
		{
			get
			{
				return this._Lokalizasyon;
			}
			set
			{
				if ((this._Lokalizasyon != value))
				{
					this._Lokalizasyon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="NVarChar(50)")]
		public string Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this._Boyut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoMorbidite", DbType="NVarChar(100)")]
		public string KoMorbidite
		{
			get
			{
				return this._KoMorbidite;
			}
			set
			{
				if ((this._KoMorbidite != value))
				{
					this._KoMorbidite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PksAciklamasi", DbType="NVarChar(2)")]
		public string PksAciklamasi
		{
			get
			{
				return this._PksAciklamasi;
			}
			set
			{
				if ((this._PksAciklamasi != value))
				{
					this._PksAciklamasi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sikayet", DbType="NVarChar(50)")]
		public string Sikayet
		{
			get
			{
				return this._Sikayet;
			}
			set
			{
				if ((this._Sikayet != value))
				{
					this._Sikayet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoOperasyon", DbType="NVarChar(150)")]
		public string CoOperasyon
		{
			get
			{
				return this._CoOperasyon;
			}
			set
			{
				if ((this._CoOperasyon != value))
				{
					this._CoOperasyon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iskemi", DbType="Int")]
		public System.Nullable<int> Iskemi
		{
			get
			{
				return this._Iskemi;
			}
			set
			{
				if ((this._Iskemi != value))
				{
					this._Iskemi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortSayisi", DbType="Int")]
		public System.Nullable<int> PortSayisi
		{
			get
			{
				return this._PortSayisi;
			}
			set
			{
				if ((this._PortSayisi != value))
				{
					this._PortSayisi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YardimYNT", DbType="NVarChar(55)")]
		public string YardimYNT
		{
			get
			{
				return this._YardimYNT;
			}
			set
			{
				if ((this._YardimYNT != value))
				{
					this._YardimYNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this._Sure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="NVarChar(50)")]
		public string Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this._Dren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kanama", DbType="Int")]
		public System.Nullable<int> Kanama
		{
			get
			{
				return this._Kanama;
			}
			set
			{
				if ((this._Kanama != value))
				{
					this._Kanama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piyes", DbType="Int")]
		public System.Nullable<int> Piyes
		{
			get
			{
				return this._Piyes;
			}
			set
			{
				if ((this._Piyes != value))
				{
					this._Piyes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpveErkenKomp", DbType="NVarChar(50)")]
		public string PreOpveErkenKomp
		{
			get
			{
				return this._PreOpveErkenKomp;
			}
			set
			{
				if ((this._PreOpveErkenKomp != value))
				{
					this._PreOpveErkenKomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpAnaliz", DbType="NVarChar(50)")]
		public string PostOpAnaliz
		{
			get
			{
				return this._PostOpAnaliz;
			}
			set
			{
				if ((this._PostOpAnaliz != value))
				{
					this._PostOpAnaliz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonda", DbType="NVarChar(50)")]
		public string Sonda
		{
			get
			{
				return this._Sonda;
			}
			set
			{
				if ((this._Sonda != value))
				{
					this._Sonda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospSuresi", DbType="Int")]
		public System.Nullable<int> HospSuresi
		{
			get
			{
				return this._HospSuresi;
			}
			set
			{
				if ((this._HospSuresi != value))
				{
					this._HospSuresi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PreOpKreatin
		{
			get
			{
				return this._PreOpKreatin;
			}
			set
			{
				if ((this._PreOpKreatin != value))
				{
					this._PreOpKreatin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PostOpKreatin
		{
			get
			{
				return this._PostOpKreatin;
			}
			set
			{
				if ((this._PostOpKreatin != value))
				{
					this._PostOpKreatin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpHCT", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PreOpHCT
		{
			get
			{
				return this._PreOpHCT;
			}
			set
			{
				if ((this._PreOpHCT != value))
				{
					this._PreOpHCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpHCT", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PostOpHCT
		{
			get
			{
				return this._PostOpHCT;
			}
			set
			{
				if ((this._PostOpHCT != value))
				{
					this._PostOpHCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpHB", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PreOpHB
		{
			get
			{
				return this._PreOpHB;
			}
			set
			{
				if ((this._PreOpHB != value))
				{
					this._PreOpHB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpHB", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PostOpHB
		{
			get
			{
				return this._PostOpHB;
			}
			set
			{
				if ((this._PostOpHB != value))
				{
					this._PostOpHB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="NVarChar(175)")]
		public string Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this._Takip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(20)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpGecKomp", DbType="NVarChar(100)")]
		public string PostOpGecKomp
		{
			get
			{
				return this._PostOpGecKomp;
			}
			set
			{
				if ((this._PostOpGecKomp != value))
				{
					this._PostOpGecKomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompClavien", DbType="NVarChar(5)")]
		public string KompClavien
		{
			get
			{
				return this._KompClavien;
			}
			set
			{
				if ((this._KompClavien != value))
				{
					this._KompClavien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(50)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this._Patoloji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(100)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this._AltGrup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuhrmanGrade", DbType="NVarChar(30)")]
		public string FuhrmanGrade
		{
			get
			{
				return this._FuhrmanGrade;
			}
			set
			{
				if ((this._FuhrmanGrade != value))
				{
					this._FuhrmanGrade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatolojikEvreler", DbType="NVarChar(10)")]
		public string PatolojikEvreler
		{
			get
			{
				return this._PatolojikEvreler;
			}
			set
			{
				if ((this._PatolojikEvreler != value))
				{
					this._PatolojikEvreler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerrahiSinir", DbType="NVarChar(2)")]
		public string CerrahiSinir
		{
			get
			{
				return this._CerrahiSinir;
			}
			set
			{
				if ((this._CerrahiSinir != value))
				{
					this._CerrahiSinir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp3AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp3AyLokalNuks
		{
			get
			{
				return this._PostOp3AyLokalNuks;
			}
			set
			{
				if ((this._PostOp3AyLokalNuks != value))
				{
					this._PostOp3AyLokalNuks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp3AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp3AyKreatin
		{
			get
			{
				return this._PostOp3AyKreatin;
			}
			set
			{
				if ((this._PostOp3AyKreatin != value))
				{
					this._PostOp3AyKreatin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp6AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp6AyLokalNuks
		{
			get
			{
				return this._PostOp6AyLokalNuks;
			}
			set
			{
				if ((this._PostOp6AyLokalNuks != value))
				{
					this._PostOp6AyLokalNuks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp6AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp6AyKreatin
		{
			get
			{
				return this._PostOp6AyKreatin;
			}
			set
			{
				if ((this._PostOp6AyKreatin != value))
				{
					this._PostOp6AyKreatin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp12AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp12AyLokalNuks
		{
			get
			{
				return this._PostOp12AyLokalNuks;
			}
			set
			{
				if ((this._PostOp12AyLokalNuks != value))
				{
					this._PostOp12AyLokalNuks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp12AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp12AyKreatin
		{
			get
			{
				return this._PostOp12AyKreatin;
			}
			set
			{
				if ((this._PostOp12AyKreatin != value))
				{
					this._PostOp12AyKreatin = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.patientTrackingView")]
	public partial class patientTrackingView
	{
		
		private int _ID;
		
		private string _HastaAdı;
		
		private string _HastaSoyadı;
		
		private string _ProtokolNo;
		
		private System.Nullable<System.DateTime> _OperasyonTarihi;
		
		private string _OpTuru;
		
		private System.Nullable<int> _TakipAy;
		
		private System.Nullable<int> _Anah;
		
		private string _PostOp3AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp3AyKreatin;
		
		private string _PostOp6AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp6AyKreatin;
		
		private string _PostOp12AyLokalNuks;
		
		private System.Nullable<decimal> _PostOp12AyKreatin;
		
		public patientTrackingView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaAdı", DbType="NVarChar(50)")]
		public string HastaAdı
		{
			get
			{
				return this._HastaAdı;
			}
			set
			{
				if ((this._HastaAdı != value))
				{
					this._HastaAdı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaSoyadı", DbType="NVarChar(50)")]
		public string HastaSoyadı
		{
			get
			{
				return this._HastaSoyadı;
			}
			set
			{
				if ((this._HastaSoyadı != value))
				{
					this._HastaSoyadı = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProtokolNo", DbType="NVarChar(50)")]
		public string ProtokolNo
		{
			get
			{
				return this._ProtokolNo;
			}
			set
			{
				if ((this._ProtokolNo != value))
				{
					this._ProtokolNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperasyonTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> OperasyonTarihi
		{
			get
			{
				return this._OperasyonTarihi;
			}
			set
			{
				if ((this._OperasyonTarihi != value))
				{
					this._OperasyonTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(400)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this._OpTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakipAy", DbType="Int")]
		public System.Nullable<int> TakipAy
		{
			get
			{
				return this._TakipAy;
			}
			set
			{
				if ((this._TakipAy != value))
				{
					this._TakipAy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this._Anah = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp3AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp3AyLokalNuks
		{
			get
			{
				return this._PostOp3AyLokalNuks;
			}
			set
			{
				if ((this._PostOp3AyLokalNuks != value))
				{
					this._PostOp3AyLokalNuks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp3AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp3AyKreatin
		{
			get
			{
				return this._PostOp3AyKreatin;
			}
			set
			{
				if ((this._PostOp3AyKreatin != value))
				{
					this._PostOp3AyKreatin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp6AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp6AyLokalNuks
		{
			get
			{
				return this._PostOp6AyLokalNuks;
			}
			set
			{
				if ((this._PostOp6AyLokalNuks != value))
				{
					this._PostOp6AyLokalNuks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp6AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp6AyKreatin
		{
			get
			{
				return this._PostOp6AyKreatin;
			}
			set
			{
				if ((this._PostOp6AyKreatin != value))
				{
					this._PostOp6AyKreatin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp12AyLokalNuks", DbType="NVarChar(10)")]
		public string PostOp12AyLokalNuks
		{
			get
			{
				return this._PostOp12AyLokalNuks;
			}
			set
			{
				if ((this._PostOp12AyLokalNuks != value))
				{
					this._PostOp12AyLokalNuks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOp12AyKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostOp12AyKreatin
		{
			get
			{
				return this._PostOp12AyKreatin;
			}
			set
			{
				if ((this._PostOp12AyKreatin != value))
				{
					this._PostOp12AyKreatin = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
